Adding solution for Homework5-Task3 Employee Vacation Management
sarunaspra/NetDevSchoolHWCoherentSolutions pull request #11
Opened 2022-02-03 07:00 UTC by sarunaspra

2022-02-06 11:18 UTC, radislavkireev requested changes

2022-02-06 11:18 UTC, radislavkireev commented on Homework5/EmployeeVacationManagement/Entities/OrganizationVacationsManagement.cs
> +        public void addVacation(EmployeeVacationDetails vacation)
uppercase AddVacation

2022-02-06 11:18 UTC, radislavkireev commented on Homework5/EmployeeVacationManagement/Entities/EmployeeVacationDetails.cs
> +        public bool isEmployeeAStudent { get; set; }
uppercase Is...

2022-02-06 11:18 UTC, radislavkireev commented on Homework5/EmployeeVacationManagement/Entities/OrganizationVacationsManagement.cs
> +                .Select(employeVacationAvg => new
instead of creation of anonymous instance create tuple in Select and return employeeVacationAverage .

return  _employeeVacations.GroupBy(employee => employee.EmployeeName,
                employeeVacation => employeeVacation.GetEmployeeVacationLength())
                .Select(employeVacationAvg => ( ... ));

2022-02-06 11:18 UTC, radislavkireev commented on Homework5/EmployeeVacationManagement/Entities/OrganizationVacationsManagement.cs
> +                && otheItem.DateOfLastVacationDay >= item.DateOfFirstVacationDay
Here is the possible intersections ( black line otherItem, red line - item). Condition does not cover all of them. 

![image](https://user-images.githubusercontent.com/2743649/152678167-4433350c-2258-44c0-85a1-288edc3d3d63.png)

2022-02-06 12:17 UTC, sarunaspra commented on Homework5/EmployeeVacationManagement/Entities/OrganizationVacationsManagement.cs
> +                && otheItem.DateOfLastVacationDay >= item.DateOfFirstVacationDay
I tried to test my program with various cases of possible intersections and, in my opinion, everything works fine. Could you give an example of intersection which my condition doesn't cover?

2022-02-06 12:24 UTC, sarunaspra commented on Homework5/EmployeeVacationManagement/Entities/OrganizationVacationsManagement.cs
> +                .Select(employeVacationAvg => new
Thank you, I'll fix it

2022-02-12 17:33 UTC, radislavkireev approved these changes

2022-02-12 17:39 UTC, radislavkireev requested changes

2022-02-12 17:39 UTC, radislavkireev commented on Homework5/EmployeeVacationManagement/Entities/OrganizationVacationsManagement.cs
> +                yield return (month, _employeeVacations.Count(vacation => vacation.DateOfFirstVacationDay.Month == month
Employee may have long vacation potentially, from month 1 to month 3 for example.

2022-02-13 06:33 UTC, merged